name: create a puzzle
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - run: node --version
      - run: ./index.js 
